### PR TITLE
injected logger into RegistrationManager, only call gateway if it's actually there

### PR DESCRIPTION
**Pull request by pulse00**
If no gateway was configured, the registration-manager fails upon registration.
This PR calls the gateway only if it's injected.  I also added some info logging in the manager.

### CODE REVIEW

**Comment by pmartelletti** [comment]
@pulse00 seems like you're right! :smile: 

We'll reviewing this in the next few days (we're a little bit busy now), and in case everything is OK we'll merge it (or if necessary, the correspondent amends) :smile: 

Thanks a lot!

**Comment by pulse00** [comment]
great, thanks!

**Comment by pmartelletti** [comment]
@pulse00 sorry for delay! It's been merged now. Thanks for your work. :smile:

**Comment by pulse00** [comment]
no problem, thanks for merging.

**Pull request merged**
